/** Free AI moderator adapter: optional ReallyArtificial/freeport gateway + Pollinations fallback. AI never changes Council scores or weights. */
const TIMEOUT_MS=Number(process.env.AI_TIMEOUT_MS||22000);
const MAX_CANDIDATES=Math.min(Math.max(Number(process.env.AI_MAX_CANDIDATES||3),1),10);
const FREEPORT_URL=String(process.env.FREEPORT_URL||'').replace(/\/$/,'');
const FREEPORT_MODEL=process.env.FREEPORT_MODEL||'gpt-4o-mini';
function promptFor(c){const lines=c.agents.map(a=>'['+a.name+' · bobot '+Number(a.weight).toFixed(1)+'x] '+a.signal+' (skor '+a.score+', conf '+a.conf+'%) → '+a.reason).join('\n');return 'DEWAN 8 AGEN berdiskusi tentang koin '+c.base+'USDT.\n\nREGIME PASAR: '+c.regime.type.toUpperCase()+' — '+c.regime.desc+'\nHARGA: $'+c.price+' | 24h: '+Number(c.chg24).toFixed(2)+'%\nKONSENSUS SAAT INI: '+c.consensus+'% ke arah '+c.direction+'\nPULLBACK: '+c.pullback.status.toUpperCase()+' ('+Number(c.pullback.retracement).toFixed(0)+'% retracement)\nFIB SWING: '+c.pullback.fibLow+' — '+c.pullback.fibHigh+'\n\nTRANSKRIP DISKUSI 8 AGEN:\n'+lines+'\n\nSebagai moderator netral, sintesis diskusi ini. Jangan membuat skor baru untuk Council dan jangan mengubah bobot. Verdict hanya LONG, SHORT, atau SKIP. Cocokkan arah dengan bukti mayoritas dan pullback.\nJawab HANYA JSON: {"verdict":"LONG|SHORT|SKIP","score":0-100,"reasoning":"1-2 kalimat bahasa Indonesia"}';}
function parse(text,provider){const cleaned=String(text||'').replace(/```json\s*/gi,'').replace(/```/g,'').trim();const m=cleaned.match(/\{[\s\S]*?\}/);let p=null;if(m){try{p=JSON.parse(m[0]);}catch{}}if(!p){const u=cleaned.toUpperCase();const v=u.includes('LONG')&&!u.includes('SHORT')?'LONG':u.includes('SHORT')&&!u.includes('LONG')?'SHORT':'SKIP';p={verdict:v,score:50,reasoning:cleaned.slice(0,250)};}let v=String(p.verdict||'').toUpperCase();v=v.includes('LONG')?'LONG':v.includes('SHORT')?'SHORT':'SKIP';const score=Math.max(0,Math.min(100,parseInt(p.score,10)||50));return{verdict:v,score,reasoning:String(p.reasoning||('Moderator: '+v+' ('+score+'/100)')).slice(0,250),provider};}
async function request(url,opt){const c=new AbortController(),t=setTimeout(()=>c.abort(),TIMEOUT_MS);try{const r=await fetch(url,{...opt,signal:c.signal});const body=await r.text();if(!r.ok)throw new Error('HTTP '+r.status);return body;}finally{clearTimeout(t);}}
async function moderate(c){const prompt=promptFor(c),errors=[];if(FREEPORT_URL){try{const body=await request(FREEPORT_URL+'/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+(process.env.FREEPORT_API_KEY||'local')},body:JSON.stringify({model:FREEPORT_MODEL,temperature:0,messages:[{role:'user',content:prompt}],response_format:{type:'json_object'}})});const j=JSON.parse(body);return parse(j.choices?.[0]?.message?.content||'', 'Freeport/'+FREEPORT_MODEL);}catch(e){errors.push('Freeport: '+e.message);}}for(const model of ['mistral','llama','openai-fast','']){try{const url='https://text.pollinations.ai/'+encodeURIComponent(prompt)+(model?'?model='+encodeURIComponent(model):'');const body=await request(url,{method:'GET',headers:{Accept:'text/plain'}});if(!body)throw new Error('empty');return parse(body,'Pollinations-'+(model||'default'));}catch(e){errors.push((model||'default')+': '+e.message);}}throw new Error(errors.join(' | '));}
async function validateSignals(signals){const candidates=signals.filter(s=>s.consensus>=45).slice(0,MAX_CANDIDATES);for(const s of candidates){try{const ai=await moderate(s);s.ai=ai;s.aiValidated=ai.verdict===s.direction&&ai.score>=50;console.log('AI '+s.base+': '+ai.verdict+'/'+ai.score+' · council '+s.direction+'/'+s.consensus);}catch(e){s.ai={verdict:'ERROR',score:0,reasoning:e.message,provider:'-'};s.aiValidated=false;console.warn('AI unavailable for '+s.base+': '+e.message);}}return{candidates};}
module.exports={moderate,validateSignals,MAX_CANDIDATES};