/** Crypto-Signal v4.1.0 — source-calibrated Council → AI moderator → Fibonacci geometry → existing delivery. */
const fs=require('fs'),path=require('path');
const {runCouncilEngine}=require('./scanner_engine');
const {calculateTradePlan}=require('./trade_plan');
const {validateSignals}=require('./ai_moderator');
const {sendDiscord,sendTelegram,sendBinanceSquare,sendWatchDiscord}=require('./delivery');
const OUTCOME_FILE=path.join(__dirname,'signals-log.json'),DEDUP_WINDOW_MS=90*60*1000,SIGNAL_VALID_MS=15*60*1000;
function loadOutcomeLog(){try{if(!fs.existsSync(OUTCOME_FILE))return{open:[],closed:[],stats:{}};const r=JSON.parse(fs.readFileSync(OUTCOME_FILE,'utf8'));return{open:Array.isArray(r.open)?r.open:[],closed:Array.isArray(r.closed)?r.closed:[],stats:r.stats&&typeof r.stats==='object'?r.stats:{}};}catch{return{open:[],closed:[],stats:{}};}}
function saveOutcomeLog(log){try{fs.writeFileSync(OUTCOME_FILE,JSON.stringify(log,null,2));}catch(e){console.warn('Outcome log save failed:',e.message);}}
function signalFingerprint(s){const entry=Number(s?.entry),rel=v=>{const n=Number(v);return Number.isFinite(n)&&Number.isFinite(entry)&&entry!==0?((n-entry)/entry*100).toFixed(2):'na';};return[String(s?.base||'').toUpperCase(),String(s?.action||'').toUpperCase(),String(s?.setup||'').toUpperCase(),rel(s?.sl),rel(s?.tp1),rel(s?.tp2),rel(s?.tp3)].join('|');}
function isDuplicateSignal(log,s,now=Date.now()){const fp=signalFingerprint(s),hit=x=>x&&x.base===s.base&&x.action===s.action&&((x.fingerprint&&x.fingerprint===fp)||now-(x.ts||0)<DEDUP_WINDOW_MS);return(log.open||[]).some(hit)||(log.closed||[]).some(hit);}
function filterNewSignals(signals,log){const now=Date.now();return signals.filter(s=>{if(s.validUntil&&Date.parse(s.validUntil)<now)return false;if(isDuplicateSignal(log,s,now)){console.log('Skip duplicate:',s.base,s.action);return false;}return true;});}
function applyProductionGeometry(signals){return signals.map(s=>{try{const p=calculateTradePlan(s);return{...s,action:s.direction||s.action,entry:p.fibEntry,sl:p.sl,tp1:p.tp1,tp2:p.tp2,tp3:p.tp3,rr:p.rr,leverage:p.leverage,marginUsdt:p.marginUsdt,notionalUsdt:p.notionalUsdt,riskBudgetUsdt:p.riskBudgetUsdt,slLossUsdt:p.slLossUsdt,geometry:p.geometry,fibEntryLevel:p.fibEntryLevel,fibLow:s.pullback?.fibLow,fibHigh:s.pullback?.fibHigh};}catch(e){console.warn('NO TRADE',s.base,s.direction+':',e.message);return null;}}).filter(Boolean);}
function registerSignals(log,signals){const now=Date.now();for(const s of signals){if(isDuplicateSignal(log,s,now))continue;log.open.push({id:s.base+'_'+s.action+'_'+now,ts:now,base:s.base,instId:s.instId,action:s.action,fingerprint:signalFingerprint(s),setup:s.setup,probability:s.probability||s.consensus,entry:s.entry,sl:s.sl,tp1:s.tp1,tp2:s.tp2,tp3:s.tp3,rr:s.rr,leverage:s.leverage,marginUsdt:s.marginUsdt,validUntil:s.validUntil||new Date(now+SIGNAL_VALID_MS).toISOString(),council:s.council||null,ai:s.ai||null});}return log;}
async function main(){console.log('=== Crypto-Signal v4.1 | Source-Calibrated Council ===');console.log(new Date().toISOString());const log=loadOutcomeLog();let signals=await runCouncilEngine();const ai=await validateSignals(signals);for(const s of ai.candidates)console.log('AI '+s.base+': '+(s.ai?.verdict||'ERROR')+'/'+(s.ai?.score||0)+' · council '+s.direction+'/'+s.consensus);signals=applyProductionGeometry(signals);signals=filterNewSignals(signals,log);console.log('NEW VALID:',signals.length);for(const s of signals)console.log(`  ${s.base} ${s.action} score=${s.consensus} AI=${s.ai?.verdict||'—'} entry=${s.entry} SL=${s.sl} TP1=${s.tp1} TP2=${s.tp2} TP3=${s.tp3} lev=${s.leverage}x`);const dry=String(process.env.TRADERSPY_DRY_RUN||process.env.SCANNER_DRY_RUN||'false').toLowerCase()==='true';if(dry){console.log('Delivery dry-run: no external posts and no outcome registration.');return;}await sendDiscord(signals);await sendTelegram(signals);await sendBinanceSquare(signals);if(typeof sendWatchDiscord==='function')await sendWatchDiscord([]);saveOutcomeLog(registerSignals(log,signals));console.log('Done.');}
main().catch(e=>{console.error('Scanner failed:',e);process.exit(1);});